#!/bin/bash

#SBATCH --nodes=3
#SBATCH --ntasks=3
#SBATCH --partition=west
#SBATCH --output=jobmpi.out
#SBATCH --error=jobmpi.err

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec ./timempi
