#!/bin/bash

#SBATCH --time=04:00:00
#SBATCH --partition=west
#SBATCH --nodes=3 --tasks-per-node=4
#SBATCH --error=logs/COMMUNICATION_A_JA_3_10_200.err --output=logs/COMMUNICATION_A_JA_3_10_200.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 10 partdiff_par/partdiff 1 2 200 1 1 3.3504e-05
mpiexec -n 10 partdiff_par/partdiff 1 2 200 1 1 3.3504e-05
mpiexec -n 10 partdiff_par/partdiff 1 2 200 1 1 3.3504e-05
