#!/bin/bash

#SBATCH --time=04:00:00
#SBATCH --partition=west
#SBATCH --nodes=2 --tasks-per-node=5
#SBATCH --error=logs/COMMUNICATION_A_GS_2_10_200.err --output=logs/COMMUNICATION_A_GS_2_10_200.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 10 partdiff_par/partdiff 1 1 200 1 1 3.3504e-05
mpiexec -n 10 partdiff_par/partdiff 1 1 200 1 1 3.3504e-05
mpiexec -n 10 partdiff_par/partdiff 1 1 200 1 1 3.3504e-05
