#!/bin/bash

#SBATCH --time=05:00:00
#SBATCH --partition=west
#SBATCH --nodes=2 --tasks-per-node=2
#SBATCH --error=logs/WEAK_SCALING_JA_2_4_800.err --output=logs/WEAK_SCALING_JA_2_4_800.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 4 partdiff_par/partdiff 1 2 800 2 2 1000
mpiexec -n 4 partdiff_par/partdiff 1 2 800 2 2 1000
mpiexec -n 4 partdiff_par/partdiff 1 2 800 2 2 1000
