#!/bin/bash

#SBATCH --time=05:00:00
#SBATCH --partition=west
#SBATCH --nodes=1 --tasks-per-node=2
#SBATCH --error=logs/WEAK_SCALING_JA_1_2_564.err --output=logs/WEAK_SCALING_JA_1_2_564.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 2 partdiff_par/partdiff 1 2 564 2 2 1000
mpiexec -n 2 partdiff_par/partdiff 1 2 564 2 2 1000
mpiexec -n 2 partdiff_par/partdiff 1 2 564 2 2 1000
