#!/bin/bash

#SBATCH --time=05:00:00
#SBATCH --partition=west
#SBATCH --nodes=1 --tasks-per-node=1
#SBATCH --error=logs/WEAK_SCALING_GS_1_1_400.err --output=logs/WEAK_SCALING_GS_1_1_400.out

. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec -n 1 partdiff_par/partdiff 1 1 400 2 2 1000
mpiexec -n 1 partdiff_par/partdiff 1 1 400 2 2 1000
mpiexec -n 1 partdiff_par/partdiff 1 1 400 2 2 1000
