#!/bin/bash

#3 Knoten x 12 Prozesse
PROCESSES=12	
sbatch script --export=PROCESSES

#3 Knoten x 12 Prozesse
PROCESSES=24	
sbatch script --export=PROCESSES

#3 Knoten x 1 Prozess x 12 Threads
PROCESSES=1
OMP_NUM_THREADS=12
sbatch script --export=PROCESSES --export=OMP_NUM_THREADS

#3 Knoten x 1 Prozess x 24 Threads
export PROCESSES=1
export OMP_NUM_THREADS=24
sbatch script --export=PROCESSES --export=OMP_NUM_THREADS

#3 Knoten x 2 Prozesse x 6 Threads
export PROCESSES=2
export OMP_NUM_THREADS=6
sbatch script --export=PROCESSES --export=OMP_NUM_THREADS

#3 Knoten x 2 Prozesse x 12 Threads
export PROCESSES=2
export OMP_NUM_THREADS=12
sbatch script --export=PROCESSES --export=OMP_NUM_THREADS

#3 Knoten x 12 Prozesse x 2 Threads
export PROCESSES=12
export OMP_NUM_THREADS=2
sbatch script --export=PROCESSES --export=OMP_NUM_THREADS
