#!/bin/bash

#SBATCH --partition=west
#SBATCH --nodes=2
#SBATCH --ntasks=$(PROCESSES)
#SBATCH --output=out_partdiff.out
#SBATCH --error=err_partdiff.err
. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

export OMP_NUM_THREADS=$(OMP_NUM_THREADS)
for i in `seq 1 5`;
do
    mpiexec ./partdiff-par-hybrid 1 2 512 1 2 100 >> analyse_P$(PROCESSES)_T$(OMP_NUM_THREADS).out
done
