#!/bin/bash

#SBATCH --partition=west
#SBATCH --nodes=2
#SBATCH --ntasks=3
#SBATCH --output=out_circle.out
. /etc/profile.d/modules.sh
. /etc/profile.d/wr-spack.sh
spack load --dependencies mpi

mpiexec ./circle 7
