#!/bin/bash

for i in 1 2 4 8 16 32 64 128 256 512 1024;
do
	for j in `seq 1 5`;
	do
	    export OMP_NUM_THREADS=12
	    export INTERLINES=$i
	    sbatch script --export=OMP_NUM_THREADS --export=INTERLINES
	done
done
